import { useMemo, useState } from 'react'
import { Group, Panel, Separator } from 'react-resizable-panels'
import {
  Check,
  ChevronDown,
  ChevronUp,
  FlaskConical,
  RefreshCw,
  Trash2,
  Wand2,
} from 'lucide-react'
import type { EnvironmentItem, KeyValueRow, RequestItem } from '../../types'
import {
  buildUrlWithQueryParams,
  convertRowsToHeadersJson,
  syncPathVariables,
} from '../../utils/urlHelper'
import { formatAndPrettifyJson } from '../../utils/jsonHelper'
import { emitToast } from '../common/Toast'
import { getAutoGeneratedHeaders } from '../../services/templateService'
import { CodeEditor } from '../common/CodeEditor'
import { KeyValueTable } from './KeyValueTable'
import { AuthEditor } from './AuthEditor'
import { TestScriptEditor } from './TestScriptEditor'
import { RequestBodyEditor } from './RequestBodyEditor'

interface RequestEditorProps {
  activeTab: RequestItem
  editorFontSize?: number
  environment?: EnvironmentItem | null
  onUpdateTab: (patch: Partial<RequestItem>) => void
  onFormat: () => void
  onClear: () => void
  onSyncToExplorer?: () => { success: boolean; error?: string }
  onShowToast?: (message: string, type?: 'success' | 'info' | 'warning' | 'error') => void
}

export function RequestEditor({
  activeTab,
  editorFontSize,
  environment,
  onUpdateTab,
  onFormat,
  onClear,
  onSyncToExplorer,
  onShowToast,
}: RequestEditorProps) {
  const [isVariablesOpen, setIsVariablesOpen] = useState(true)
  const [isSynced, setIsSynced] = useState(false)

  const isGraphQL = activeTab.mode === 'GRAPHQL'
  const isQueryTabActive =
    activeTab.editorTab === 'BODY' || (isGraphQL && activeTab.editorTab === 'VARIABLES')

  const handleSyncClick = () => {
    if (!onSyncToExplorer) return
    const result = onSyncToExplorer()
    if (result.success) {
      setIsSynced(true)
      setTimeout(() => setIsSynced(false), 1200)
    }
  }

  const triggerToast = (message: string, type: 'success' | 'info' | 'warning' | 'error' = 'error') => {
    if (onShowToast) {
      onShowToast(message, type)
    } else {
      emitToast(message, type)
    }
  }

  const handleFormatVariables = () => {
    const raw = activeTab.gqlVariables || ''
    if (!raw.trim()) return

    const result = formatAndPrettifyJson(raw)
    if (result.success) {
      onUpdateTab({ gqlVariables: result.formatted })
    } else {
      const errorMsg = `Lỗi cú pháp JSON Variables: ${result.error || 'Cú pháp không hợp lệ'}`
      triggerToast(errorMsg, 'error')
    }
  }

  const handleClearVariables = () => {
    onUpdateTab({ gqlVariables: '{}' })
  }

  // 2-way sync: Params change -> update URL
  const handleParamsChange = (newParams: KeyValueRow[]) => {
    const nextUrl = buildUrlWithQueryParams(activeTab.url, newParams)
    onUpdateTab({
      params: newParams,
      url: nextUrl,
    })
  }

  // Sync Headers list -> headersText
  const handleHeadersChange = (newHeaders: KeyValueRow[]) => {
    const jsonText = convertRowsToHeadersJson(newHeaders)
    onUpdateTab({
      headersList: newHeaders,
      headersText: jsonText,
    })
  }

  // Compute Full List of Postman-Style Auto-generated Headers
  const autoGeneratedHeaders = useMemo<KeyValueRow[]>(() => {
    return getAutoGeneratedHeaders(activeTab, environment)
  }, [activeTab, environment])

  // Synchronize Path Variables from URL
  const currentPathVariables = useMemo<KeyValueRow[]>(() => {
    return syncPathVariables(activeTab.url, activeTab.pathVariables)
  }, [activeTab.url, activeTab.pathVariables])

  const hasPathVariables = currentPathVariables.length > 0

  const handlePathVariablesChange = (newPathVars: KeyValueRow[]) => {
    onUpdateTab({
      pathVariables: newPathVars,
    })
  }

  const activeParamCount =
    (activeTab.params || []).filter((p) => p.enabled && p.key.trim()).length +
    currentPathVariables.length
  // Header tab counter ONLY counts user-defined headers (Postman Standard)
  const userHeaderCount = (activeTab.headersList || []).filter((h) => h.enabled && h.key.trim()).length
  const hasAuth = activeTab.auth && activeTab.auth.type !== 'none'
  const hasScripts = Boolean(
    (activeTab.preRequestScript && activeTab.preRequestScript.trim()) ||
      (activeTab.testScript && activeTab.testScript.trim()),
  )
  const isScriptsActive = activeTab.editorTab === 'SCRIPTS' || activeTab.editorTab === 'TESTS'

  return (
    <div className="request-editor" style={{ display: 'flex', flexDirection: 'column', height: '100%', width: '100%', minHeight: 0, overflow: 'hidden' }}>
      {/* 1. HÀNG SUB-TABS TRÊN CÙNG (CỐ ĐỊNH) */}
      <div className="section-header" style={{ flexShrink: 0 }}>
        <div className="row wrap">
          {isGraphQL ? (
            /* GraphQL Mode Tab Order: Query -> Auth -> Headers -> Scripts */
            <>
              <button
                type="button"
                onClick={() => onUpdateTab({ editorTab: 'BODY' })}
                className={`editor-tab ${isQueryTabActive ? 'is-active' : ''}`}
              >
                Query
              </button>

              <button
                type="button"
                onClick={() => onUpdateTab({ editorTab: 'AUTH' })}
                className={`editor-tab ${activeTab.editorTab === 'AUTH' ? 'is-active' : ''}`}
              >
                Auth {hasAuth && <span className="tab-counter">✓</span>}
              </button>

              <button
                type="button"
                onClick={() => onUpdateTab({ editorTab: 'HEADERS' })}
                className={`editor-tab ${activeTab.editorTab === 'HEADERS' ? 'is-active' : ''}`}
              >
                Headers {userHeaderCount > 0 && <span className="tab-counter">{userHeaderCount}</span>}
              </button>

              <button
                type="button"
                onClick={() => onUpdateTab({ editorTab: 'SCRIPTS' })}
                className={`editor-tab ${isScriptsActive ? 'is-active' : ''}`}
              >
                Scripts {hasScripts && <span className="tab-counter"><FlaskConical size={10} /></span>}
              </button>
            </>
          ) : (
            /* REST Mode Tab Order: Params -> Auth -> Headers -> Body -> Scripts */
            <>
              <button
                type="button"
                onClick={() => onUpdateTab({ editorTab: 'PARAMS' })}
                className={`editor-tab ${activeTab.editorTab === 'PARAMS' ? 'is-active' : ''}`}
              >
                Params {activeParamCount > 0 && <span className="tab-counter">{activeParamCount}</span>}
              </button>

              <button
                type="button"
                onClick={() => onUpdateTab({ editorTab: 'AUTH' })}
                className={`editor-tab ${activeTab.editorTab === 'AUTH' ? 'is-active' : ''}`}
              >
                Auth {hasAuth && <span className="tab-counter">✓</span>}
              </button>

              <button
                type="button"
                onClick={() => onUpdateTab({ editorTab: 'HEADERS' })}
                className={`editor-tab ${activeTab.editorTab === 'HEADERS' ? 'is-active' : ''}`}
              >
                Headers {userHeaderCount > 0 && <span className="tab-counter">{userHeaderCount}</span>}
              </button>

              <button
                type="button"
                onClick={() => onUpdateTab({ editorTab: 'BODY' })}
                className={`editor-tab ${activeTab.editorTab === 'BODY' ? 'is-active' : ''}`}
              >
                Body
              </button>

              <button
                type="button"
                onClick={() => onUpdateTab({ editorTab: 'SCRIPTS' })}
                className={`editor-tab ${isScriptsActive ? 'is-active' : ''}`}
              >
                Scripts {hasScripts && <span className="tab-counter"><FlaskConical size={10} /></span>}
              </button>
            </>
          )}
        </div>

        {/* REST mode Toolbar buttons */}
        {!isGraphQL && activeTab.editorTab !== 'BODY' && (
          <div className="row wrap">
            <button onClick={onClear} className="button button-sm" type="button">
              <Trash2 size={13} />
              Clear
            </button>
          </div>
        )}
      </div>

      {/* 2. NỘI DUNG CHÍNH (BẮT BUỘC CHIẾM TRỌN DIỆN TÍCH flex-1 min-h-0) */}
      <div className="editor-body" style={{ flex: '1 1 0%', minHeight: 0, height: '100%', width: '100%', display: 'flex', flexDirection: 'column', padding: 0, overflow: 'hidden' }}>
        
        {/* GRAPHQL UNIFIED QUERY & VARIABLES PANE (VERTICAL RESIZABLE SPLIT PANE) */}
        {isGraphQL && isQueryTabActive && (
          <div style={{ flex: '1 1 0%', display: 'flex', flexDirection: 'column', height: '100%', width: '100%', minHeight: 0, overflow: 'hidden' }}>
            {isVariablesOpen ? (
              <Group
                orientation="vertical"
                id="gql-editor-layout"
                className="gql-editor-panels-group"
              >
                {/* PANEL 1: GRAPHQL QUERY EDITOR */}
                <Panel
                  id="gql-query-panel"
                  defaultSize="65%"
                  minSize="25%"
                  className="gql-query-panel panel-resizable-item"
                >
                  {/* TOOLBAR TRÊN (Format, Sync, Clear) - CỐ ĐỊNH */}
                  <div className="gql-pane-toolbar">
                    <span className="gql-pane-title">
                      GRAPHQL QUERY / MUTATION
                    </span>
                    <div className="row" style={{ gap: '6px' }}>
                      <button onClick={onFormat} className="button button-sm" type="button">
                        <Wand2 size={12} />
                        <span>Format</span>
                      </button>
                      {onSyncToExplorer && (
                        <button
                          onClick={handleSyncClick}
                          className={`button button-sm ${isSynced ? 'text-emerald-400 border-emerald-500/40 bg-emerald-500/10' : ''}`}
                          title="Đồng bộ các trường trong Editor ngược lại cây chọn GraphQL Explorer bên trái"
                          type="button"
                        >
                          {isSynced ? <Check size={12} className="text-emerald-400" /> : <RefreshCw size={12} />}
                          <span>{isSynced ? 'Synced!' : 'Sync to Explorer'}</span>
                        </button>
                      )}
                      <button onClick={onClear} className="button button-sm" type="button">
                        <Trash2 size={12} />
                        <span>Clear</span>
                      </button>
                    </div>
                  </div>

                  {/* KHU VỰC SOẠN THẢO GRAPHQL QUERY */}
                  <div className="gql-pane-editor-container">
                    <div className="gql-pane-editor-inner">
                      <CodeEditor
                        value={activeTab.gqlQuery || ''}
                        onChange={(val) => onUpdateTab({ gqlQuery: val })}
                        language="graphql"
                        placeholder="query { ... }"
                        height="100%"
                        minHeight="100%"
                        fontSize={editorFontSize}
                      />
                    </div>
                  </div>
                </Panel>

                {/* THANH KÉO RESIZE NGANG (VERTICAL SPLITTER) */}
                <Separator className="resize-handle horizontal-handle gql-resize-handle" />

                {/* PANEL 2: VARIABLES DRAWER */}
                <Panel
                  id="gql-variables-panel"
                  defaultSize="35%"
                  minSize="15%"
                  className="gql-variables-panel panel-resizable-item"
                >
                  {/* HEADER VARIABLES (CLICK TOGGLE / FORMAT / CLEAR) */}
                  <div
                    className="graphql-vars-header"
                    onClick={() => setIsVariablesOpen(false)}
                  >
                    <div className="row" style={{ gap: '8px' }}>
                      <ChevronDown size={14} style={{ color: 'var(--text-muted)' }} />
                      <span className="graphql-vars-title">Variables</span>
                      <span className="graphql-vars-tag">
                        JSON
                      </span>
                    </div>

                    <div className="row" style={{ gap: '4px' }} onClick={(e) => e.stopPropagation()}>
                      <button
                        type="button"
                        title="Format JSON"
                        className="button button-xs"
                        onClick={handleFormatVariables}
                      >
                        Format
                      </button>
                      <button
                        type="button"
                        title="Clear JSON"
                        className="button button-xs"
                        onClick={handleClearVariables}
                      >
                        Clear
                      </button>
                    </div>
                  </div>

                  {/* KHUNG SOẠN THẢO JSON VARIABLES */}
                  <div className="gql-pane-editor-container" style={{ borderTop: '1px solid #232736', background: '#12141a' }}>
                    <div className="gql-pane-editor-inner">
                      <CodeEditor
                        value={activeTab.gqlVariables || '{}'}
                        onChange={(val) => onUpdateTab({ gqlVariables: val })}
                        language="json"
                        placeholder="{\n  \n}"
                        height="100%"
                        minHeight="100%"
                        fontSize={editorFontSize}
                      />
                    </div>
                  </div>
                </Panel>
              </Group>
            ) : (
              /* KHI THU GỌN: QUERY FULL 100%, THANH BAR Ở ĐÁY */
              <div style={{ display: 'flex', flexDirection: 'column', height: '100%', width: '100%', minHeight: 0, overflow: 'hidden' }}>
                {/* TOOLBAR TRÊN */}
                <div className="gql-pane-toolbar">
                  <span className="gql-pane-title">
                    GRAPHQL QUERY / MUTATION
                  </span>
                  <div className="row" style={{ gap: '6px' }}>
                    <button onClick={onFormat} className="button button-sm" type="button">
                      <Wand2 size={12} />
                      <span>Format</span>
                    </button>
                    {onSyncToExplorer && (
                      <button
                        onClick={handleSyncClick}
                        className={`button button-sm ${isSynced ? 'text-emerald-400 border-emerald-500/40 bg-emerald-500/10' : ''}`}
                        title="Đồng bộ các trường trong Editor ngược lại cây chọn GraphQL Explorer bên trái"
                        type="button"
                      >
                        {isSynced ? <Check size={12} className="text-emerald-400" /> : <RefreshCw size={12} />}
                        <span>{isSynced ? 'Synced!' : 'Sync to Explorer'}</span>
                      </button>
                    )}
                    <button onClick={onClear} className="button button-sm" type="button">
                      <Trash2 size={12} />
                      <span>Clear</span>
                    </button>
                  </div>
                </div>

                {/* KHU VỰC SOẠN THẢO GRAPHQL QUERY */}
                <div className="gql-pane-editor-container">
                  <div className="gql-pane-editor-inner">
                    <CodeEditor
                      value={activeTab.gqlQuery || ''}
                      onChange={(val) => onUpdateTab({ gqlQuery: val })}
                      language="graphql"
                      placeholder="query { ... }"
                      height="100%"
                      minHeight="100%"
                      fontSize={editorFontSize}
                    />
                  </div>
                </div>

                {/* THANH TOGGLE GỌN Ở ĐÁY */}
                <div
                  className="graphql-vars-header is-collapsed"
                  onClick={() => setIsVariablesOpen(true)}
                >
                  <div className="row" style={{ gap: '8px' }}>
                    <ChevronUp size={14} style={{ color: 'var(--text-muted)' }} />
                    <span className="graphql-vars-title">Variables</span>
                    <span className="graphql-vars-tag">
                      JSON
                    </span>
                  </div>
                </div>
              </div>
            )}
          </div>
        )}

        {/* PARAMS TAB (REST) */}
        {!isGraphQL && activeTab.editorTab === 'PARAMS' && (
          <div className="scroll-area" style={{ padding: '10px 12px', display: 'flex', flexDirection: 'column', gap: 16 }}>
            {/* 1. QUERY PARAMETERS */}
            <KeyValueTable
              rows={activeTab.params}
              onChange={handleParamsChange}
              keyPlaceholder="Parameter Key"
              valuePlaceholder="Parameter Value"
              descriptionPlaceholder="Description"
              title="Query Parameters"
              environment={environment}
            />

            {/* 2. PATH VARIABLES (Chỉ xuất hiện khi URL có chứa token :variable) */}
            {hasPathVariables && (
              <div className="path-variables-section" style={{ borderTop: '1px solid var(--border)', paddingTop: 14 }}>
                <KeyValueTable
                  rows={currentPathVariables}
                  onChange={handlePathVariablesChange}
                  valuePlaceholder="Value (e.g. 123 or {{var}})"
                  descriptionPlaceholder="Description"
                  title="Path Variables"
                  environment={environment}
                  isPathVariableTable={true}
                  hideAddRow={true}
                />
              </div>
            )}
          </div>
        )}

        {/* HEADERS TAB */}
        {activeTab.editorTab === 'HEADERS' && (
          <div className="scroll-area" style={{ padding: '10px 12px' }}>
            <KeyValueTable
              rows={activeTab.headersList}
              autoRows={autoGeneratedHeaders}
              onChange={handleHeadersChange}
              keyPlaceholder="Header Name (e.g. Content-Type)"
              valuePlaceholder="Header Value (e.g. application/json)"
              descriptionPlaceholder="Description"
              title="Request Headers"
              environment={environment}
            />
          </div>
        )}

        {/* AUTH TAB */}
        {activeTab.editorTab === 'AUTH' && (
          <div className="scroll-area" style={{ padding: '10px 12px' }}>
            <AuthEditor
              auth={activeTab.auth}
              onChange={(auth) => onUpdateTab({ auth })}
              environment={environment}
            />
          </div>
        )}

        {/* REST BODY TAB */}
        {!isGraphQL && activeTab.editorTab === 'BODY' && (
          <RequestBodyEditor
            activeTab={activeTab}
            editorFontSize={editorFontSize}
            environment={environment}
            onUpdateTab={onUpdateTab}
            onFormat={onFormat}
            onClear={onClear}
            onShowToast={onShowToast}
          />
        )}

        {/* SCRIPTS / TESTS TAB */}
        {isScriptsActive && (
          <TestScriptEditor
            preRequestScript={activeTab.preRequestScript || ''}
            testScript={activeTab.testScript || ''}
            editorFontSize={editorFontSize}
            onChangePreRequest={(preRequestScript) => onUpdateTab({ preRequestScript })}
            onChangeTest={(testScript) => onUpdateTab({ testScript })}
          />
        )}
      </div>
    </div>
  )
}
